// GENERATED by scripts/draw-olive.mjs (seed 48). Do not edit by hand.
export const OLIVE_GEOMETRY = {
  width: 880,
  height: 780,
  /** Where the trunk meets the ground, as a fraction of width and height. */
  root: [0.4943, 0.9179],
} as const;
