// GENERATED by scripts/draw-olive.mjs (seed 48). Do not edit by hand.
export const OLIVE_GEOMETRY = {
  width: 954,
  height: 678,
  /** Where the trunk meets the ground, as a fraction of width and height. */
  root: [0.4329, 0.9499],
} as const;
