// GENERATED by scripts/build-land.mjs — do not edit.
//
// Grid frame for public/land/land.png. Row 0 is the north edge.
// Elevation: Terrain Tiles on AWS Open Data (terrarium), from NASA SRTM and
// NOAA ETOPO1 (public domain). Outline: Natural Earth 1:10m (public domain),
// the union of the polygons it names Palestine and Israel, with the Syrian
// Golan excluded (never part of Mandate Palestine). Lakes: Natural Earth 1:50m.

export const LAND_GRID = {
  width: 257,
  height: 479,
  lon0: 33.95,
  lat1: 33.55,
  step: 0.009,
  /** Offset added to elevation (metres) before 16-bit encoding. */
  offset: 1000,
  /** Lowest and highest elevation inside the land, metres. */
  landMin: -452,
  landMax: 1112,
  /** The land's extent: [west, south, east, north]. */
  landBox: [34.202, 29.491, 35.651, 33.280],
} as const;

export const LAND_SOURCES = [
  "Elevation: Terrain Tiles, AWS Open Data (Tilezen) — from NASA SRTM and NOAA ETOPO1, public domain",
  "Outline: Natural Earth 1:10m admin-0 (public domain) — union of the polygons named Palestine and Israel, with the Syrian Golan excluded",
  "Lakes: Natural Earth 1:50m (public domain)",
] as const;
