#!/usr/bin/env node
/**
 * SHEET 00 — the physical layer of the MAJDAL map drawing.
 *
 * Builds, from public-domain Natural Earth data:
 *  - water-lining for the sea: parallel strokes, the convention survey sheets
 *    used for water before tone was cheap to print;
 *  - lakes (outline + water-lining) and rivers, 1:50m, via sane-topojson.
 *
 * Output is projected into the same 760×1260 viewBox as the coastline and the
 * place register (src/lib/geo.ts), and committed as plain path strings: the
 * site ships no mapping library.
 *
 * This is modern physical geography drawn by MAJDAL. It is not a historical
 * survey and is never captioned as one.
 */

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { feature } from "topojson-client";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");

// Must match src/lib/geo.ts
const VIEW = { w: 760, h: 1260 };
const BBOX = { minLat: 31.2, maxLat: 33.3, minLon: 34.2, maxLon: 35.7 };
const PAD = { x: 40, y: 40 };
const meanLat = (BBOX.minLat + BBOX.maxLat) / 2;
const lonScale = Math.cos((meanLat * Math.PI) / 180);
const spanLat = BBOX.maxLat - BBOX.minLat;
const spanLon = (BBOX.maxLon - BBOX.minLon) * lonScale;
const scale = Math.min((VIEW.w - PAD.x * 2) / spanLon, (VIEW.h - PAD.y * 2) / spanLat);
const cx = (BBOX.minLon + BBOX.maxLon) / 2;
const cy = (BBOX.minLat + BBOX.maxLat) / 2;
const project = ([lon, lat]) => [VIEW.w / 2 + (lon - cx) * lonScale * scale, VIEW.h / 2 - (lat - cy) * scale];
const f = (n) => (Math.round(n * 10) / 10).toString();

const inFrame = ([lon, lat], m = 0.05) =>
  lon >= BBOX.minLon - m && lon <= BBOX.maxLon + m && lat >= BBOX.minLat - m && lat <= BBOX.maxLat + m;

// ---------- sea water-lining, from the committed coastline selvedge ----------
const coastSrc = readFileSync(join(root, "src/content/coastline.ts"), "utf8");
const SELVEDGE = JSON.parse(coastSrc.match(/export const SELVEDGE: number\[\] = (\[[^\]]*\])/)[1]);
const rows = SELVEDGE.length;
const coastX = (y) => {
  const r = (y / VIEW.h) * (rows - 1);
  const i = Math.max(0, Math.min(rows - 2, Math.floor(r)));
  const t = r - i;
  return SELVEDGE[i] * (1 - t) + SELVEDGE[i + 1] * t;
};
const STEP = 6;
const sea = [];
for (let y = STEP / 2; y < VIEW.h; y += STEP) {
  // stop short of the shore, the way an engraver leaves a white margin
  const x1 = coastX(y) - 4;
  if (x1 > 2) sea.push(`M0 ${f(y)}H${f(x1)}`);
}

// ---------- lakes and rivers (1:50m) ----------
const topo = JSON.parse(readFileSync(join(root, "node_modules/sane-topojson/dist/asia_50m.json"), "utf8"));
const lakesFC = feature(topo, topo.objects.lakes);
const riversFC = feature(topo, topo.objects.rivers);

const lakeRings = [];
for (const ft of lakesFC.features) {
  const polys = ft.geometry.type === "Polygon" ? [ft.geometry.coordinates] : ft.geometry.coordinates;
  for (const poly of polys) {
    const outer = poly[0];
    if (!outer.some((p) => inFrame(p))) continue;
    lakeRings.push(outer.map(project));
  }
}
const lakes = lakeRings.map((r) => "M" + r.map((p) => f(p[0]) + " " + f(p[1])).join("L") + "Z").join("");

// water-lining inside each lake: scanline intersections
const lakeLines = [];
for (const ring of lakeRings) {
  const ys = ring.map((p) => p[1]);
  for (let y = Math.ceil(Math.min(...ys) / 4) * 4 + 2; y < Math.max(...ys); y += 4) {
    const xs = [];
    for (let i = 0, j = ring.length - 1; i < ring.length; j = i++) {
      const [x0, y0] = ring[j], [x1, y1] = ring[i];
      if ((y0 <= y && y1 > y) || (y1 <= y && y0 > y)) xs.push(x0 + ((y - y0) / (y1 - y0)) * (x1 - x0));
    }
    xs.sort((a, b) => a - b);
    for (let k = 0; k + 1 < xs.length; k += 2) {
      if (xs[k + 1] - xs[k] > 3) lakeLines.push(`M${f(xs[k] + 1.5)} ${f(y)}H${f(xs[k + 1] - 1.5)}`);
    }
  }
}

const rivers = [];
for (const ft of riversFC.features) {
  const lines = ft.geometry.type === "LineString" ? [ft.geometry.coordinates] : ft.geometry.coordinates;
  for (const ln of lines) {
    const pts = ln.filter((p) => inFrame(p, 0.2));
    if (pts.length < 2) continue;
    rivers.push("M" + pts.map(project).map((p) => f(p[0]) + " " + f(p[1])).join("L"));
  }
}

const out = `// GENERATED by scripts/build-sheet.mjs — do not edit.
//
// Physical layer of SHEET 00, the MAJDAL map drawing. Natural Earth, public
// domain: sea water-lining derived from the 1:10m coastline; lakes and rivers
// at 1:50m via sane-topojson. Modern physical geography — not a historical
// survey. Projected into the ${VIEW.w}×${VIEW.h} viewBox of src/lib/geo.ts.

export const SEA_LINES = ${JSON.stringify(sea.join(""))};
export const LAKES = ${JSON.stringify(lakes)};
export const LAKE_LINES = ${JSON.stringify(lakeLines.join(""))};
export const RIVERS = ${JSON.stringify(rivers.join(""))};
export const PX_PER_DEGREE_LAT = ${scale.toFixed(4)};
export const SHEET_SOURCES = [
  "Coast: Natural Earth 1:10m land (public domain), via world-atlas",
  "Lakes and rivers: Natural Earth 1:50m (public domain), via sane-topojson",
] as const;
`;
writeFileSync(join(root, "src/content/sheet.ts"), out);
console.log(`sea lines ${sea.length}, lakes ${lakeRings.length}, lake lines ${lakeLines.length}, rivers ${rivers.length}, px/deg ${scale.toFixed(1)}`);
